spring.application.name=farmacia

# PostgreSQL properties
spring.datasource.url= jdbc:postgresql://localhost:5432/prueva_1
spring.datasource.username= postgres
spring.datasource.password= Gadcalderon2021
spring.datasource.driver-class-name= org.postgresql.Driver
# Hibernate properties
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= update 
